I18n.en =
  menu:
    schema: "Séma"
    new: "Új ..."
    load: "Megnyitás ..."
    save: "Mentés"
    save_as: "Mentés másként ..."
    templates: "Sablonok ..."
    properties: "Tulajdonságok ..."
    share: "Megosztás ..."
    import: "Importálás ..."
    edit: "Szerkesztés"
    undo: "Visszavon"
    redo: "Újra"
    select_all: "Mind kijelölése"
    select_none: "Kijelölés törlése"
    delete_selected: "Kiválasztott törlése"
    insert: "Beszúrás"
    table: "Tábla"
    note: "Jegyzet"
    view: "Nézet"
    show_minimap: "Térkép mutatása"
    hide_minimap: "Térkép elrejtése"
    show_sidebar: "Oldalsáv mutatása"
    hide_sidebar: "Oldalsáv elrejtése"
    show_grid: "Rács megjelenítése"
    hide_grid: "Rács elrejtése"
    sort_items: "Elemek elrendezése"
    linetype: "Vonaltípus"
    bezier: "Görbe"
    cornered: "Lesarkított"
    options: "Beállítások ..."
    export: "Exportálás"
    sql: "Sql ..."
    image: "Kép ..."
    help: "Súgó"
    index: "Index"
    changes: "Változási napló"
    shortcuts: "Billentyűkombinációk"
    feedback: "Visszajelzés"
    about: "Névjegy"
    guest: "Vendég"
    login: "Bejelentkezés"
    logout: "Kilépés"
    settings: "Beállítások"
  panel:
    history: "Előzmények"
    last_versions_label: "A séma legutolsó 10 verziója:"
    properties: "Tulajdonságok"
    properties_schema_name: "Séma neve:"
    properties_database: "Adatbázis:"
    comments: "Megjegyzések"
    comment_placeholder: "Megjegyzés"
    send: "Küldés"
  dialog:
    new_schema: "Új séma"
    new_schema_title: "Cím"
    new_schema_database: "Adatbázis"
    new_schema_type_info: """Az "általános" adatbázis típus minden adatbázis számára lehetővé teszi az SQL létrehozását; de csak az általános adattípusokhoz ad hozzáférést."""
    new_schema_create_new: "Új séma létrehozása"
    load_schema: "Séma betöltése"
    load_schema_your_schemas: "Elérhető sémák:"
    load_schema_schema_name: "Séma neve"
    load_schema_database: "Adatbázis"
    load_schema_last_save: "Utoljára mentve"
    load_schema_shared_with_you: "Mgosztott sémák:"
    load_schema_owner: "Tulajdonos"
    load_schema_no_schemas: "Séma nem található"
    load_schema_no_shared_schemas: "Megosztott sémák nem találhatóak"
    saveas: "Mentés másként"
    saveas_title: "Cím"
    saveas_button: "Mentés másként"
    templates: "Sablonok"
    templates_schema_name: "Séma neve"
    templates_database: "Adatbázis"
    templates_description: "Leírás"
    properties: "Séma tulajdonságai"
    properties_title: "Cím"
    properties_publish: "Közzététel sablonként"
    properties_template_info: "(A sablonok minden felhasználó számára láthatóak)"
    properties_delete_schema: "Séma törlése"
    properties_delete_alert: "(Séma és az összes kapcsolódó megjegyzés törlése)"
    properties_save: "Módosítások mentése"
    share: "Megosztás"
    share_info: "A séma legfeljebb 5 felhasználóval osztható meg"
    share_email: "E-mail"
    share_access: "Hozzáférés"
    share_read_only: "Csak olvasható"
    share_read_write: "Írható olvasható"
    share_send_email: "Meghívó E-Mail küldése"
    share_invite_button: "Meghívás"
    share_collaborators: "Közreműködők:"
    import: "Sql importálása"
    login_email: "E-mail"
    login_password: "Jelszó"
    login_button: "Bejelentkezés"
    login_forgot_password: "Elfelejtett jelszó"
    options: "Beállítások"
    options_line_colors: "Vonalak színe"
    options_invert_line_direction: "Vonalak irányának megváltoztatása"
    options_show_fk_icon: "Mutassa az idenegen kulcsokat"
    options_show_ai_icon: "Mutassa as Auto Increment ikont"
    options_show_not_null_icon: "Mutassa a Not Null ikont"
    options_show_default_values: "Mutassa a Default (alapértelmezett) értékeket"
    options_language: "Nyelv"
    options_save_changes: "Módosítások mentése"
    export_sql: "SQL exportálása"
    export_sql_generate: "SQL létrehozása"
    export_sql_download: "SQL fájl letöltése"
    export_image: "Kép exportálása"
    export_image_zoomin: "Nagyítás"
    export_image_zoomout: "Kicsinyítés"
    export_image_reset: "Visszaállítás"
    export_image_open_in_new_tab: "Kép megnyitása új fülön"
    help: "Súgó"
    shortcuts: "Billentyűkombinációk"
    help_changelog: "Változási napló"
    feedback: "Visszajelzés"
    feedback_type: "Visszajelzés Típusa"
    feedback_bug: "Hibanapló"
    feedback_feature: "Új funkció kérése"
    feedback_help: "Súgó"
    feedback_other: "Egyéb"
    feedback_message: "Üzenet"
    feedback_button: "Visszajelzés küldése"
    about: "A dbdesigner.net -ről"
    user_settings: "Felhasználó beállítások"
    user_settings_username: "Felhasználó"
    user_settings_email: "E-mail"
    user_settings_save: "Módosítások mentése"
    login: "Bejelentkezés"
    close: "Bezár"
    back: "Vissza"
    dirty_schema_confirmation: "El nem mentett módosítások!"
    dirty_schema_confirmation_message: "El nem mentett módosítások, mentsük őket?"
    dirty_schema_confirmation_save_changes_button: "Módosítások mentése"
    dirty_schema_confirmation_discard_changes_and_continue_button: "Módosítások elvetése"
    dirty_schema_confirmation_cancel_button: "Mégse"
  designer:
    save_note_edit: "Mentés"
    cancel_note_edit: "Mégse"
    delete_note: "Törlés"
    table_name: "Tábla neve"
    table_comment: "Tábla megjegyzés"
    table_save: "Mentés"
    table_cancel: "Mégse"
    table_delete: "Tábla törlése"
    table_clone: "Tábla klónozása"
    table_add_field: "Mező hozzáadása"
    field_name: "Név"
    field_type: "Típus"
    field_size: "Méret"
    field_default: "Alapértelmezett"
    field_unique: "Egyedi"
    field_allow_nulls: "Null érték lehetséges"
    field_autoincrement: "Automatikusan generált"
    field_primary_key: "Elsődleges kulcs"
    field_foreign_key: "Idegen kulcs"
    field_save: "Mentés"
    field_update: "Módosítás"
    field_cancel: "Mégse"
    field_delete: "Mező törlése"
    field_delete_alert: "Mező törlése?\n(tartsa nyomva a shift gombot a megerősítés nélküli törléshez)"
    field_ref_table: "Ref. Tábla"
    field_ref_field: "Ref. Mező"
  alerts:
    delete_schema: "Séma törlése?"
    server_error: "Szerverhiba"
    schema_owner_error: "Kizárólag a séma tulajdonosa módosíthatja a megosztási beállításokat"
    login_to_use_this_function: "A funkció eléréséhez be kell jelentkezni"