I18n.ro =
  menu:
    schema: "Schemă"
    new: "Nou ..."
    load: "Încărcare ..."
    save: "Salvare"
    save_as: "Salvare ca ..."
    templates: "Șabloane ..." ---
    properties: "Proprietăți ..."
    share: "Distribuire ..."
    import: "Importare ..."
    edit: "Editare"
    undo: "Anulare"
    redo: "Refacere" ---
    select_all: "Selectare Tot"
    select_none: "Selectare nimic"
    delete_selected: "Ștergere selecție"
    insert: "Inserare"
    table: "Tabelă"
    note: "Notă"
    view: "Mască"
    show_minimap: "Afișare mini hartă"
    hide_minimap: "Ascundere mini hartă"
    show_sidebar: "Afișare panou lateral"
    hide_sidebar: "Ascundere panou lateral"
    show_grid: "Afișare Grilă"
    hide_grid: "Ascundere Grilă"
    sort_items: "Sortare Itemi"
    linetype: "Tip linie"
    bezier: "Bezier"
    cornered: "Rotunjit"
    options: "Opțiuni ..."
    export: "Exportare"
    sql: "SQL ..."
    image: "Imagine ..."
    help: "Ajutor"
    index: "Index"
    changes: "Modificări"
    shortcuts: "Scurtături tastatură"
    feedback: "Părere"
    about: "Despre"
    guest: "Oaspete"
    login: "Logare"
    logout: "Delogare"
    settings: "Setări"
  panel:
    history: "Istoric"
    last_versions_label: "Ultimele 10 versiuni ale acestei scheme:"
    properties: "Proprietăți"
    properties_schema_name: "Nume Schemă:"
    properties_database: "Baza de Date:"
    comments: "Comentarii"
    comment_placeholder: "Introdu comentariul aici"
    send: "Trimite"
  dialog:
    new_schema: "Schemă nouă"
    new_schema_title: "Titlu"
    new_schema_database: "Baza de Date" 
    new_schema_type_info: """Selectarea tipului "generic" pentru baza de date îți permite generarea codului SQL pentru toate bazele de date; vei avea acces însă doar la tipurile de date generic."""
    new_schema_create_new: "Creare Schemă nouă"
    load_schema: "Încarcare Schemă"
    load_schema_your_schemas: "Lista mea de scheme:"
    load_schema_schema_name: "Nume schemă"
    load_schema_database: "Baza de Date"
    load_schema_last_save: "Ultima salvare"
    load_schema_shared_with_you: "Scheme partajate cu tine:"
    load_schema_owner: "Deținător"
    load_schema_no_schemas: "Nu ai salvat nicio schemă"
    load_schema_no_shared_schemas: "Nu sunt scheme partajate cu tine"
    saveas: "Salvare ca"
    saveas_title: "Titlu"
    saveas_button: "Salvare ca"
    templates: "Șabloane"
    templates_schema_name: "Nume Schemă"
    templates_database: "Baza de Date"
    templates_description: "Descriere"
    properties: "Proprietăți Schemă"
    properties_title: "Titlu"
    properties_publish: "Publică ca șablon"
    properties_template_info: "(Șabloane vizibile pentru fiecare utilizator)" 
    properties_delete_schema: "Ștergere schemă"
    properties_delete_alert: "(Vei șterge permanent această schemă și toate comentariile asociate)" 
    properties_save: "Salvare modificări"
    share: "Distribuire"
    share_info: "Poți distribui schema cu maxim 5 utilizatori" 
    share_email: "E-mail"
    share_access: "Acces"
    share_read_only: "Doar vizualizare"
    share_read_write: "Vizualizare și scriere"
    share_send_email: "Trimitere invitație pe e-mail"
    share_invite_button: "Invită"
    share_collaborators: "Colaboratori:"
    import: "Importare SQL"
    login_email: "E-mail"
    login_password: "Parolă"
    login_button: "Logare"
    login_forgot_password: "Am uitat parola"
    options: "Opțiuni"
    options_line_colors: "Culori linie"
    options_invert_line_direction: "Inversare direcție linie"
    options_show_fk_icon: "Afișare pictogramă Cheie Străină" 
    options_show_ai_icon: "Afișare pictogramă Incrementare Automată" 
    options_show_not_null_icon: "Afișare pictogramă Ne Null" 
    options_show_default_values: "Afișare valori implicite"
    options_language: "Limbă"
    options_save_changes: "Salvare modificări"
    export_sql: "Exportare SQL"
    export_sql_generate: "Generare SQL"
    export_sql_download: "Descarcare fișier SQL"
    export_image: "Exportare Imagine"
    export_image_zoomin: "Mărire"
    export_image_zoomout: "Micșorare"
    export_image_reset: "Resetare"
    export_image_open_in_new_tab: "Deschidere imagine in filă nouă"
    help: "Ajutor"
    shortcuts: "Scurtături tastatură"
    help_changelog: "Modificări"
    feedback: "Părere"
    feedback_type: "Tip părere"
    feedback_bug: "Raportare problemă"
    feedback_feature: "Cerere caracteristică"
    feedback_help: "Ajutor"
    feedback_other: "Altele"
    feedback_message: "Mesaj"
    feedback_button: "Trimitere părere"
    about: "Despre dbdesigner.net"
    user_settings: "Setări utilizator"
    user_settings_username: "Nume utilizator"
    user_settings_email: "E-mail"
    user_settings_save: "Salvare modificări"
    login: "Logare"
    close: "Inchide"
    back: "Inapoi"
    dirty_schema_confirmation: "Modificări nesalvate!"
    dirty_schema_confirmation_message: "Ai modificări nesalvate in schemă, vrei să le salvezi?" 
    dirty_schema_confirmation_save_changes_button: "Salvare modificări"
    dirty_schema_confirmation_discard_changes_and_continue_button: "Renunțare la modificări"
    dirty_schema_confirmation_cancel_button: "Anulare"
  designer:
    save_note_edit: "Salvare"
    cancel_note_edit: "Anulare"
    delete_note: "Ștergere"
    table_name: "Nume tabelă"
    table_comment: "Comentariu tabelă"
    table_save: "Salvare"
    table_cancel: "Anulare"
    table_delete: "Stergere tabelă"
    table_clone: "Clonare tabelă"
    table_add_field: "Adaugare câmp"
    field_name: "Nume"
    field_type: "Tip"
    field_size: "Măsură"
    field_default: "Mod Implicit"
    field_unique: "Unic"
    field_allow_nulls: "Acceptare NULL"
    field_autoincrement: "Auto Incrementare"
    field_primary_key: "Cheie Primară"
    field_foreign_key: "Cheie Străină"
    field_save: "Salvare"
    field_update: "Actualizare"
    field_cancel: "Anulare"
    field_delete: "Ștergere câmp"
    field_delete_alert: "Ești sigur că vrei să ștergi acest câmp?\n(ține apăsat Shift pentru a șterge fără confirmare)" 
    field_ref_table: "Tabelă referențiată"
    field_ref_field: "Câmp referențiat"
  alerts:
    delete_schema: "Ești sigur că vrei să ștergi această schemă?"
    server_error: "A aparut o eroare de server!"
    schema_owner_error: "Doar deținătorul schemei poate modifica setările" 
    login_to_use_this_function: "Pentru a folosi această funcționalitate trebuie să fii logat"