I18n.en =
  menu:
    schema: "Chizma"
    new: "Yangi ..."
    load: "Yuklash ..."
    save: "Saqlash"
    save_as: "Yangi nusxada saqlash ..."
    templates: "Shablonlar ..."
    properties: "Xususiyatlar ..."
    share: "Bo'lishish ..."
    import: "Import ..."
    edit: "Tahrirlash"
    undo: "Bekor qilish"
    redo: "Qaytarish"
    select_all: "Hammasini belgilash"
    select_none: "Belgilashlarni olib tashlash"
    delete_selected: "Belgilanganlarni o'chirish"
    insert: "Qo'yish"
    table: "Jadval"
    note: "Eslatma"
    view: "Ko'rish"
    show_minimap: "Mini xaritani ochish"
    hide_minimap: "Mini xaritani yopish"
    show_sidebar: "Yon panelni ochish"
    hide_sidebar: "Yon panelni yopish"
    show_grid: "Katakchalarni ko'rsatish"
    hide_grid: "Katakchalarni yashirish"
    sort_items: "Tartiblash"
    linetype: "Chiziq turi"
    bezier: "Siziq chiziq"
    cornered: "Burchakli"
    options: "Tanlovlar ..."
    export: "Export"
    sql: "Sql ..."
    image: "Rasm ..."
    help: "Yordam"
    index: "Index"
    changes: "O'zgartirishlar"
    shortcuts: "Klaviatura shartli knopkalari"
    feedback: "Qayta aloqa"
    about: "Haqida"
    guest: "Mehmon"
    login: "Kirish"
    logout: "Chiqish"
    settings: "Sozlamalar"
  panel:
    history: "Tarix"
    last_versions_label: "Bu chizmani oxirgi 10 xil ko'rinishi:"
    properties: "Xususiyatlar"
    properties_schema_name: "Chizma nomi:"
    properties_database: "Ma'lumotlar ombori:"
    comments: "Izohlar"
    comment_placeholder: "Izohingizni shu yerda qoldiring"
    send: "Jo'natish"
  dialog:
    new_schema: "Yangi chizma"
    new_schema_title: "Sarlavha"
    new_schema_database: "Ma'lumotlar ombori"
    new_schema_type_info: """Selecting the "generic" database type will allow you to generate SQL for all the databases; but you will only have access to the generic datatypes."""
    new_schema_create_new: "Create New Schema"
    load_schema: "Load Schema"
    load_schema_your_schemas: "Sizning chizgilaringiz:"
    load_schema_schema_name: "Chizma nomi"
    load_schema_database: "Ma'lumotlar ombori"
    load_schema_last_save: "Oxirgi saqlash"
    load_schema_shared_with_you: "Siz bilan bo'lishilgan chizmalar:"
    load_schema_owner: "Egasi"
    load_schema_no_schemas: "Siz hech qanday chizma saqlaganingiz yo'q"
    load_schema_no_shared_schemas: "Siz bilan hech qanday chizma bo'lishilgani yo'q"
    saveas: "Nusxada saqlash"
    saveas_title: "Sarlavha"
    saveas_button: "Nusxada saqlash"
    templates: "Shablonlar"
    templates_schema_name: "Chizma nomi"
    templates_database: "Ma'lumotlar ombori"
    templates_description: "Izox"
    properties: "Chizma xususiyatlari"
    properties_title: "Sarlavha"
    properties_publish: "Shablon kabi saqlash"
    properties_template_info: "(Har bir foydalanuvchi uchun ko'rinadigan shablon)"
    properties_delete_schema: "Chizmani o'chirish"
    properties_delete_alert: "(Siz ushbu chizma va unga aloqador bo'lgan barcha izoxlarni o'chirmoqchimisiz?)"
    properties_save: "O'zgaritirishlarni saqlash"
    share: "Bo'lishish"
    share_info: "Siz chizmangizni ko'pi bilan 5 kishiga bo'lisha olasiz"
    share_email: "Elektron pochta"
    share_access: "Ruxsat"
    share_read_only: "Faqat o'qish"
    share_read_write: "O'qish va yozish"
    share_send_email: "Elektron pochta orqali taklif yuborish"
    share_invite_button: "Taklif qilish"
    share_collaborators: "Hamkorlar:"
    import: "Import Sql"
    login_email: "Elektron manzil"
    login_password: "Parol"
    login_button: "Login"
    login_forgot_password: "Men parolimni unuttim"
    options: "Tanlovlar"
    options_line_colors: "Chiziq ranglari"
    options_invert_line_direction: "Chiziq yo'nalishini teskarilash"
    options_show_fk_icon: "Tashqi bog'lanish belgisini ko'rsatish"
    options_show_ai_icon: "Ortib boradigan belgisini qo'yish"
    options_show_not_null_icon: "Nol emas belgisini qo'yish"
    options_show_default_values: "Birlamchi qiymatni ko'rsatish"
    options_language: "Til"
    options_save_changes: "O'zgartirishlarni saqlash"
    export_sql: "Export SQL"
    export_sql_generate: "SQL hosil qilish"
    export_sql_download: "SQL ko'rinishda saqlash"
    export_image: "Rasm eksport"
    export_image_zoomin: "Yaqinlashtirish"
    export_image_zoomout: "Uzoqlashtirish"
    export_image_reset: "Qayta boshlash"
    export_image_open_in_new_tab: "Rasmni yangi yorliqda ko'rsatish"
    help: "Yordam"
    shortcuts: "Klaviatura tezkor klavishlari"
    help_changelog: "O'zgartirishlar"
    feedback: "Qayta aloqa"
    feedback_type: "Qayta aloqa turi"
    feedback_bug: "Xatolikni yuborish"
    feedback_feature: "Yangi imkoniyat so'rash"
    feedback_help: "Yordam"
    feedback_other: "Boshqa"
    feedback_message: "Xabar"
    feedback_button: "Qayta aloqa yuborish"
    about: "dbdesigner.net haqida"
    user_settings: "Foydalanuvchi sozlamalari"
    user_settings_username: "Login"
    user_settings_email: "Elektron manzil"
    user_settings_save: "O'zgaritirshlarni saqlash"
    login: "Login"
    close: "Yopish"
    back: "Ortga"
    dirty_schema_confirmation: "O'zgartirishlar saqlanmadi!"
    dirty_schema_confirmation_message: "Sizni chizmalaringizda saqlanmagan o'zgartirishlar mavjud, ularni saqlamoqchimisiz?"
    dirty_schema_confirmation_save_changes_button: "O'zgartirishlarni saqlash"
    dirty_schema_confirmation_discard_changes_and_continue_button: "O'zgartirishlarni bekor qilish"
    dirty_schema_confirmation_cancel_button: "Bekor qilish"
  designer:
    save_note_edit: "Saqlash"
    cancel_note_edit: "Bekor qilish"
    delete_note: "O'chirish"
    table_name: "Jadval nomi"
    table_comment: "Jadval izoxi"
    table_save: "Saqlash"
    table_cancel: "Bekor qilish"
    table_delete: "Jadvalni o'chirish"
    table_clone: "Jadvalni nusxalash"
    table_add_field: "Ustun qo'shish"
    field_name: "Nomi"
    field_type: "Turi"
    field_size: "O'lcham"
    field_default: "Standart"
    field_unique: "Unikal"
    field_allow_nulls: "Bo'shlikka rozilik berish"
    field_autoincrement: "Avto o'sib borish"
    field_primary_key: "Birlamchi kalit"
    field_foreign_key: "Chetki kalit"
    field_save: "Saqlash"
    field_update: "Yangilash"
    field_cancel: "Bekor qilish"
    field_delete: "Ustunni o'chirish"
    field_delete_alert: "Siz ushbu ustunni o'chirishingizga ishonchingiz komilmi?\n(tasdig'ingizsiz o'chirish uchun shift klavishini bosib o'chiring)"
    field_ref_table: "Ref. Jadval"
    field_ref_field: "Ref. Ustun"
  alerts:
    delete_schema: "Ushbu chizmani o'chirishingizga ishonchingiz komilmi?"
    server_error: "Serverda xatolik yuz berdi"
    schema_owner_error: "Faqatgina chizma egasi bo'lishish qoidalarini tahrirlay oladi"
    login_to_use_this_function: "Bu imkoniyatdan foydalanish uchun saytga shaxsingizni tasdiqlab kirishingiz lozim"
